//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headmaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableCourses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvailableCourses()
        {
            this.Registrations = new HashSet<Registrations>();
        }
    
        public int AvailalbeCourseID { get; set; }
        public int CourseID { get; set; }
        public string Section { get; set; }
        public string CRN { get; set; }
        public int TimeID { get; set; }
        public int DayID { get; set; }
        public int BuildingID { get; set; }
        public int ProfessorID { get; set; }
        public int SemesterYearID { get; set; }
        public string RoomNumber { get; set; }
    
        public virtual Buildings Buildings { get; set; }
        public virtual Courses Courses { get; set; }
        public virtual Days Days { get; set; }
        public virtual Professors Professors { get; set; }
        public virtual SemesterYear SemesterYear { get; set; }
        public virtual Times Times { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registrations> Registrations { get; set; }
        public virtual SemesterYear SemesterYear1 { get; set; }
    }
}
