//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headmaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseGrades
    {
        public int CourseGradeID { get; set; }
        public int RegistrationID { get; set; }
        public int GradeID { get; set; }
        public int StudentID { get; set; }
    
        public virtual Grades Grades { get; set; }
        public virtual Registrations Registrations { get; set; }
        public virtual Students Students { get; set; }
    }
}
