//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headmaster.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class headmasterEntities : DbContext
    {
        public headmasterEntities()
            : base("name=headmasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AvailableCourses> AvailableCourses { get; set; }
        public virtual DbSet<Buildings> Buildings { get; set; }
        public virtual DbSet<Corequisites> Corequisites { get; set; }
        public virtual DbSet<CourseGrades> CourseGrades { get; set; }
        public virtual DbSet<CoursePriority> CoursePriority { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Days> Days { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Grades> Grades { get; set; }
        public virtual DbSet<MajorRequirements> MajorRequirements { get; set; }
        public virtual DbSet<Majors> Majors { get; set; }
        public virtual DbSet<MinorRequirements> MinorRequirements { get; set; }
        public virtual DbSet<Minors> Minors { get; set; }
        public virtual DbSet<Prerequisites> Prerequisites { get; set; }
        public virtual DbSet<Professors> Professors { get; set; }
        public virtual DbSet<Registrations> Registrations { get; set; }
        public virtual DbSet<Semesters> Semesters { get; set; }
        public virtual DbSet<SemesterYear> SemesterYear { get; set; }
        public virtual DbSet<StudentMajors> StudentMajors { get; set; }
        public virtual DbSet<StudentMinors> StudentMinors { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Times> Times { get; set; }
        public virtual DbSet<Years> Years { get; set; }
    }
}
