//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headmaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MajorRequirements
    {
        public int MajorRequirementsID { get; set; }
        public int MajorID { get; set; }
        public int CourseID { get; set; }
        public int PriorityID { get; set; }
    
        public virtual CoursePriority CoursePriority { get; set; }
        public virtual Courses Courses { get; set; }
        public virtual Majors Majors { get; set; }
    }
}
