//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headmaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemesterYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SemesterYear()
        {
            this.AvailableCourses1 = new HashSet<AvailableCourses>();
        }
    
        public int SemesterYearID { get; set; }
        public int SemesterID { get; set; }
        public int YearID { get; set; }
        public string SemesterYearName { get { return string.Concat(Semesters1.Semester + " " + Years1.Year); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailableCourses> AvailableCourses1 { get; set; }
        public virtual Semesters Semesters1 { get; set; }
        public virtual Years Years1 { get; set; }
    }
}
