//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headmaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemesterYear
    {
        public int SemesterYearID { get; set; }
        public int SemesterID { get; set; }
        public int YearID { get; set; }
    
        public virtual AvailableCourses AvailableCourses { get; set; }
        public virtual Semesters Semesters { get; set; }
        public virtual Years Years { get; set; }
    }
}
