//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Headmaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semesters
    {
        public int SemesterID { get; set; }
        public string Semester { get; set; }
    
        public virtual SemesterYear SemesterYear { get; set; }
    }
}
